### ISSUE TITLE
Shared goals with other shard

### ISSUE THREAD

**Issue by bcardiff** [jasonl99/lattice-core#24]
Hi @jasonl99,

Sorry for opening an issue, but I am not sure how to contact you. I recently new about lattice-core, I had experiment with some shard with similar goals, keep a persistent connection with each client in the server and allow manipulation of the dom through it.

In case you found it interesting I would leave a couple of links here:
https://github.com/bcardiff/redomi
https://github.com/bcardiff/crystal-ast-helper

**Comment by jasonl99** [comment]
@bcardiff Hi Brian!  

Unfortunately, I have not had the time to work with crystal for some time (I wish I had more time for it, crystal is such an awesome language!).   I will definitely take a look at this though.
